export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const NEED_TO_LOGIN = 'NEED_TO_LOGIN';
export const GAME_JOINED = 'GAME_JOINED';
export const GAME_QUIT = 'GAME_QUIT';
export const PLAYER_JOINED = 'PLAYER_JOINED';
export const PLAYER_LEFT = 'PLAYER_LEFT';
export const GOT_REFRESH_GAME_DATA = 'GOT_REFRESH_GAME_DATA';
export const GAME_SEND_MSG = 'GAME_SEND_MSG';
export const GAME_SENT_MSG = 'GAME_SENT_MSG';
export const GAME_RECEIVE_GENERAL_MSG = 'GAME_RECEIVE_GENERAL_MESSAGE';
export const GAME_RECEIVE_PRIVATE_MSG = 'GAME_RECEIVE_PRIVATE_MESSAGE';
export const UPDATE_GAME_RULES = 'UPDATE_GAME_RULES';
export const GAME_RULES_UPDATED = 'GAME_RULES_UPDATED';
export const SEND_GAME_ACTION = 'SEND_GAME_ACTION';
export const GAME_ACTION_SENT = 'GAME_ACTION_SENT';
export const GAME_ACTION_TO_PROCESSED = 'GAME_ACTION_TO_PROCESSED';
export const GAME_ACTION_PROCESSED = 'GAME_ACTION_PROCESSED';
export const GAME_STARTED = 'GAME_STARTED';
export const RECEIVE_ROLE_PLAYER = 'RECEIVE_ROLE_PLAYER';
export const RECEIVE_EVENT_MESSAGE = 'RECEIVE_EVENT_MESSAGE';
export const KNOW_WITNESS = 'KNOW_WITNESS';
export const KNOW_EVIDENCE = 'KNOW_EVIDENCE';
export const ADD_WITNESS_QUESTION = 'ADD_WITNESS_QUESTION';
export const WITNESS_QUESTION_PROCESSED = 'WITNESS_QUESTION_PROCESSED';


